//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdamBlocklyLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdamBlocklyLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adam.
        /// </summary>
        public static string AdamCommonToolboxName {
            get {
                return ResourceManager.GetString("AdamCommonToolboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adam v.2.7.
        /// </summary>
        public static string AdamThreeToolboxName {
            get {
                return ResourceManager.GetString("AdamThreeToolboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adam v.2.6 .
        /// </summary>
        public static string AdamTwoToolboxName {
            get {
                return ResourceManager.GetString("AdamTwoToolboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color.
        /// </summary>
        public static string ColourToolboxName {
            get {
                return ResourceManager.GetString("ColourToolboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lists.
        /// </summary>
        public static string ListsToolboxName {
            get {
                return ResourceManager.GetString("ListsToolboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Logic.
        /// </summary>
        public static string LogicToolboxName {
            get {
                return ResourceManager.GetString("LogicToolboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loops.
        /// </summary>
        public static string LoopsToolboxName {
            get {
                return ResourceManager.GetString("LoopsToolboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Math.
        /// </summary>
        public static string MathToolboxName {
            get {
                return ResourceManager.GetString("MathToolboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Procedure.
        /// </summary>
        public static string ProcedureToolboxName {
            get {
                return ResourceManager.GetString("ProcedureToolboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Systems.
        /// </summary>
        public static string SystemsToolboxName {
            get {
                return ResourceManager.GetString("SystemsToolboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text.
        /// </summary>
        public static string TextToolboxName {
            get {
                return ResourceManager.GetString("TextToolboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Threads.
        /// </summary>
        public static string ThreadToolboxName {
            get {
                return ResourceManager.GetString("ThreadToolboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Variables Dynamic.
        /// </summary>
        public static string VariablesDynamicToolboxName {
            get {
                return ResourceManager.GetString("VariablesDynamicToolboxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Variables.
        /// </summary>
        public static string VariablesToolboxName {
            get {
                return ResourceManager.GetString("VariablesToolboxName", resourceCulture);
            }
        }
    }
}
